import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { 
  BarChart3, Users, TrendingUp, Upload,
  Sun, Moon, ChevronLeft, ChevronRight, Activity
} from 'lucide-react';
import { useTheme } from '@/lib/ThemeContext';
import { cn } from '@/lib/utils';
import { Tooltip, TooltipContent, TooltipTrigger, TooltipProvider } from '@/components/ui/tooltip';

// Sidebar navigation for the DataPulse dashboard.
// Shows page links, theme toggle, and collapse controls.
const navItems = [
  { path: '/', icon: BarChart3, label: 'Sales Overview' },
  { path: '/users', icon: Users, label: 'User Analytics' },
  { path: '/insights', icon: TrendingUp, label: 'Insights & Trends' },
  { path: '/data', icon: Upload, label: 'Data Management' },
];

export default function Sidebar({ collapsed, setCollapsed }) {
  const location = useLocation();
  const { isDark, toggleTheme } = useTheme();

  return (
    <TooltipProvider delayDuration={0}>
      <aside className={cn(
        "fixed left-0 top-0 h-screen z-40 flex flex-col border-r border-border/60 bg-sidebar transition-all duration-500 ease-in-out",
        collapsed ? "w-[68px]" : "w-[240px]"
      )}>

        {/* Logo */}
        <div className={cn(
          "flex items-center gap-3 border-b border-border/50 transition-all duration-500",
          collapsed ? "px-3 h-16 justify-center" : "px-5 h-16"
        )}>
          <div className="relative flex-shrink-0">
            <div className="w-8 h-8 rounded-full bg-primary/15 border border-primary/25 flex items-center justify-center">
              <Activity className="w-3.5 h-3.5 text-primary" />
            </div>
            <div className="absolute -bottom-0.5 -right-0.5 w-2.5 h-2.5 rounded-full bg-primary/60 border-2 border-sidebar" />
          </div>
          {!collapsed && (
            <div className="overflow-hidden">
              <h1 className="font-display text-base font-semibold tracking-wide leading-tight">DataPulse</h1>
              <p className="text-[10px] text-muted-foreground tracking-widest uppercase mt-0.5">Intelligence</p>
            </div>
          )}
        </div>

        {/* Nav label */}
        {!collapsed && (
          <p className="text-[9px] uppercase tracking-[0.2em] text-muted-foreground/60 px-5 pt-5 pb-1.5">
            Navigation
          </p>
        )}

        {/* Nav Items */}
        <nav className="flex-1 py-2 px-2 space-y-0.5">
          {navItems.map(({ path, icon: Icon, label }) => {
            const isActive = location.pathname === path;

            const item = (
              <Link
                key={path}
                to={path}
                className={cn(
                  "group flex items-center gap-3 px-3 py-2.5 rounded-xl text-xs font-medium tracking-wide transition-all duration-200",
                  isActive
                    ? "bg-primary/12 text-primary shadow-sm"
                    : "text-muted-foreground hover:text-foreground hover:bg-secondary/80"
                )}
              >
                <div className={cn(
                  "w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0 transition-all",
                  isActive ? "bg-primary/15" : "bg-transparent group-hover:bg-secondary"
                )}>
                  <Icon className="w-3.5 h-3.5" />
                </div>
                {!collapsed && (
                  <span className="truncate">{label}</span>
                )}
                {!collapsed && isActive && (
                  <div className="ml-auto w-1 h-4 rounded-full bg-primary/50" />
                )}
              </Link>
            );

            return collapsed ? (
              <Tooltip key={path}>
                <TooltipTrigger asChild>{item}</TooltipTrigger>
                <TooltipContent side="right" className="text-xs">{label}</TooltipContent>
              </Tooltip>
            ) : item;
          })}
        </nav>

        {/* Hero image strip */}
        {!collapsed && (
          <div className="mx-4 mb-3 rounded-xl overflow-hidden relative h-24">
            <img
              src="/dashboard-hero.png"
              alt="Dashboard hero image generated by ChatGPT"
              className="w-full h-full object-cover object-center"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-sidebar/80 to-transparent" />
          </div>
        )}

        {/* Bottom Controls */}
        <div className="p-2 space-y-0.5 border-t border-border/50">
          <button
            onClick={toggleTheme}
            className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-xs text-muted-foreground hover:text-foreground hover:bg-secondary/80 transition-all"
          >
            {isDark
              ? <Sun className="w-3.5 h-3.5 flex-shrink-0" />
              : <Moon className="w-3.5 h-3.5 flex-shrink-0" />}
            {!collapsed && <span>{isDark ? 'Light Mode' : 'Dark Mode'}</span>}
          </button>
          <button
            onClick={() => setCollapsed(!collapsed)}
            className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-xs text-muted-foreground hover:text-foreground hover:bg-secondary/80 transition-all"
          >
            {collapsed
              ? <ChevronRight className="w-3.5 h-3.5" />
              : <ChevronLeft className="w-3.5 h-3.5" />}
            {!collapsed && <span>Collapse</span>}
          </button>
        </div>
      </aside>
    </TooltipProvider>
  );
}